apiVersion: integration/v1
kind: Step
name: core
version: 1
summary: Relay core

description: |
  This is a template for a simple step.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/core
